import type { ApplicationData } from "@/lib/types";

/** A bundled demo case: a generated label image plus its application data. */
export interface SampleCase {
  id: string;
  /** Short button label. */
  name: string;
  /** What this case demonstrates, shown as hint text. */
  demonstrates: string;
  imagePath: string;
  application: ApplicationData;
}

/**
 * Demo cases covering all three piles. Images are generated by
 * scripts/generate-samples.mjs and live in public/samples/.
 */
export const SAMPLE_CASES: SampleCase[] = [
  {
    id: "old-tom-pass",
    name: "Old Tom Bourbon",
    demonstrates: "A clean match — every field agrees with the application.",
    imagePath: "/samples/old-tom-pass.png",
    application: {
      beverageType: "spirits",
      brandName: "Old Tom Distillery",
      classType: "Kentucky Straight Bourbon Whiskey",
      alcoholContent: "45% Alc./Vol. (90 Proof)",
      netContents: "750 mL",
      bottlerInfo: "Distilled and Bottled by Old Tom Distillery, Bardstown, KY",
    },
  },
  {
    id: "stones-throw-case",
    name: "Stone's Throw Rye",
    demonstrates:
      "Label prints the brand in ALL CAPS while the application uses title case — still a match.",
    imagePath: "/samples/stones-throw.png",
    application: {
      beverageType: "spirits",
      brandName: "Stone's Throw",
      classType: "Straight Rye Whiskey",
      alcoholContent: "47.5% Alc./Vol.",
      netContents: "750 mL",
    },
  },
  {
    id: "old-tom-wrong-abv",
    name: "Wrong ABV",
    demonstrates: "Application says 45% but the label says 40% — rejected.",
    imagePath: "/samples/old-tom-wrong-abv.png",
    application: {
      beverageType: "spirits",
      brandName: "Old Tom Distillery",
      classType: "Kentucky Straight Bourbon Whiskey",
      alcoholContent: "45% Alc./Vol. (90 Proof)",
      netContents: "750 mL",
    },
  },
  {
    id: "title-case-warning",
    name: "Bad Warning",
    demonstrates:
      "Government warning printed as \"Government Warning\" in title case — rejected, the header must be all capitals.",
    imagePath: "/samples/title-case-warning.png",
    application: {
      beverageType: "wine",
      brandName: "Sunset Ridge Cellars",
      classType: "Cabernet Sauvignon",
      alcoholContent: "13.5% Alc. by Vol.",
      netContents: "750 mL",
    },
  },
  {
    id: "near-miss-brand",
    name: "Near-Miss Brand",
    demonstrates:
      "Label says \"Old Tim Distillery\" — one letter off. Goes to human review, not auto-rejection.",
    imagePath: "/samples/near-miss-brand.png",
    application: {
      beverageType: "spirits",
      brandName: "Old Tom Distillery",
      classType: "Kentucky Straight Bourbon Whiskey",
      alcoholContent: "45% Alc./Vol. (90 Proof)",
      netContents: "750 mL",
    },
  },
  {
    id: "hop-haven-missing-warning",
    name: "Missing Warning",
    demonstrates: "Beer label with no government warning at all — rejected.",
    imagePath: "/samples/hop-haven-missing-warning.png",
    application: {
      beverageType: "beer",
      brandName: "Hop Haven Brewing Co.",
      classType: "India Pale Ale",
      alcoholContent: "6.8% Alc./Vol.",
      netContents: "12 FL. OZ.",
    },
  },
];
